version: '3'

services:
  web:
    image: jonsotal/murts
    restart: unless-stopped
    ports:
      - 3000:3000
    container_name: murts

  nginx:
    build: ./nginx
    restart: unless-stopped
    ports:
      - 80:80
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    depends_on: 
      - web
    container_name: murts_nginx

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
    container_name: murts_watchtower
